### ISSUE TITLE
LED does not blink, Alhambra board

### ISSUE THREAD

**Issue by imuguruza** [fusesoc/blinky#21]
Hi there,

I am trying to support the blinky example in an  Alhambra board. For that I have added a [pcf file](https://github.com/imuguruza/blinky/tree/alhambra_II/alhambra_II) and the board support in the blinky.core file ([here](https://github.com/imuguruza/blinky/blob/alhambra_II/blinky.core#L5) and [here](https://github.com/imuguruza/blinky/blob/alhambra_II/blinky.core#L123)), following the `tinyfpga_bx` as example.

In order to load it in `fusesoc` this repo, I have used `fusesoc library add blinky /path/to/repo` command. 

I am able to synth the example using `fusesoc run --target=alhambra_II fusesoc:utils:blinky` command.

The issue is that, once I upload the bin file, it doesn't blink. I have checked the `clk` input pin and it is fine. The LED I have assigned, once the FPGA is programmed, goes from high-impedance to OFF.

Am I missing something?

**Comment by imuguruza** [comment]
Ok, I think I now which is the problem. It looks like the paremeter `clk_freq_hz` is not bind correctly at compilation time. I have changed its value from 0 => 12000000, and now is blinking.

I have observed that `nextpnr` was throwing the next warning:
```
Warning: No clocks found in design
Warning: No clocks found in design
```

**Comment by olofk** [comment]
Yes, I should document that somewhere. The nextpnr error message isn't very clear about the fact that yosys basically removed the whole design. I have been scratching my head over why my design didn't work for the exact same reason :)

**Comment by olofk** [comment]
So if it works, I'm happy to take a PR

**Comment by imuguruza** [comment]
>So if it works, I'm happy to take a PR

It works if I hardcode the `clk_freq_hz` value in blinky.v file. If that is fine, I will open a PR

**Comment by olofk** [comment]
Ah sorry. I misunderstood. That definitely doesn't seem right. Could you look in `build/fusesoc_utils_blinky_0/alhambra_II-icestorm` and see what value you have for clk_freq_hz in the `.eda.yml` file and in `yosys.log`. I'm wondering if there is some issue with your FuseSoC or Edalize version. I know there were some issues related to parameters in the latest edalize release. Perhaps it was more broken than I thought

**Comment by imuguruza** [comment]
`eda.yml` file looks good, the clk is ok:

```
dependencies:
  fusesoc:utils:blinky:0: []
files:
- core: fusesoc:utils:blinky:0
  file_type: verilogSource
  is_include_file: false
  logical_name: ''
  name: ../src/fusesoc_utils_blinky_0/blinky.v
- core: fusesoc:utils:blinky:0
  file_type: user
  is_include_file: false
  logical_name: ''
  name: proginfo.py
- core: fusesoc:utils:blinky:0
  file_type: PCF
  is_include_file: false
  logical_name: ''
  name: ../src/fusesoc_utils_blinky_0/alhambra_II/pinout.pcf
hooks:
  post_run:
  - cmd:
    - python
    - proginfo.py
    - iceprog
    env:
      FILES_ROOT: ../src/fusesoc_utils_blinky_0
    name: iceprog
name: fusesoc_utils_blinky_0
parameters:
  clk_freq_hz:
    datatype: int
    default: 12000000
    description: Clock frequency in Hz
    paramtype: vlogparam
tool_options:
  icestorm:
    nextpnr_options:
    - --hx8k
    - --package
    - tq144:4k
    pnr: next
toplevel: blinky
version: 0.2.1
vpi: []
```

the only warning I see in `yosys.log` is the next one:

```
1. Executing Verilog-2005 frontend: ../src/fusesoc_utils_blinky_0/blinky.v
Parsing Verilog input from `../src/fusesoc_utils_blinky_0/blinky.v' to AST representation.
Storing AST representation for module `$abstract\blinky'.
Successfully finished Verilog frontend.
Warning: Selection "$abstractlinky" did not match any module.
```

In case you want to have a look on it, [here](https://gist.github.com/imuguruza/bd0f59ac693ce107da86fee730cdc23a)

I see also this in the `tcl` file
```
chparam -set clk_freq_hz 12000000 \$abstract\blinky
verilog_defaults -pop
```

I installed fusesoc using python2, `pip install fusesoc`, just in case the versions is different from the one installed with `pip3 install fusesoc` (as fusesoc doc states)
